---
- name: ensure sudoers group exist
  group:
    name: "{{ sudoers_group }}"
    state: present
- name: ensure sudoers group has passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ sudoers_group }}"
    line: "%{{ sudoers_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: add sudoers users to sudoers group
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ sudoers_group }}"
    append: yes
    create_home: yes
  with_items: "{{ sudoers_users }}"
- name: add sudoer user ssh keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ sudoers_users }}"